[pytest]
testpaths = tests
pythonpath = .
python_files = test_*.py
addopts = --cov=pyweber --cov-report=term-missing
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function

[coverage:run]
omit =
    pyweber/cli/commands.py