blank_issues_enabled: true
contact_links:
  - name: PyWeber Community Support
    url: https://github.com/pyweber/pyweber/discussions
    about: Please, do a question here.
  - name: PyWeber Documentation
    url: https://pyweber.readthedocs.io/
    about: Check our official documentation to more informations